services:
  postgres_db_brain_agriculture_test:
    image: postgres:14
    container_name: postgres_db_brain_agriculture_test
    env_file:
      - .env
    volumes:
      - postgres_data_brain_agriculture:/var/lib/postgresql/data
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend_brain_agriculture_test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_brain_agriculture_test
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db_brain_agriculture_test
    restart: unless-stopped
  frontend_brain_agriculture_test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_brain_agriculture_test
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend_brain_agriculture_test

volumes:
  postgres_data_brain_agriculture:
